### ISSUE TITLE
No functionality

### ISSUE THREAD

**Issue by gabamnml** [clickysteve/alfred-remote-workflows#1]
Hey dude I installed your workflow and I found that the project is empty and has no functionality.
Check this screenshots
![Screenshot 1](https://s3.amazonaws.com/f.cl.ly/items/1E0g2a340L2E2D250a3V/Screen%20Shot%202015-02-11%20at%2012.51.37.png)
![Screenshot 2](https://s3.amazonaws.com/f.cl.ly/items/2o1V00383r2R23352O0l/Screen%20Shot%202015-02-11%20at%2012.55.08.png)

Regards

**Comment by clickysteve** [comment]
Hey,

This is designed for Alfred Remote, so isn't a standard workflow. To add it in:
- Hit Remote at the top of Alfred
- Click on the + icon in the bottom left
- Select Workflows
- Select VLC Remote Control
- Select VLC

That will add in the Remote page for you to use in the iOS App.

![screen shot 2015-02-11 at 16 41 05](https://cloud.githubusercontent.com/assets/6227598/6151310/d09128d0-b20c-11e4-8d65-7b35f8dcf88a.png)

**Comment by gabamnml** [comment]
Perfect! it works. Thanks
